% File generated by Facile version 0.53
%
% initial values (free nodes only)
S0 = 0;
S1 = 0;
A = 0;
B = 0;
C = 0;
D = 0;
X = 0;
Y = 0.44e+1;
W = 0;
Z = 5.5;
E = 10.2e+1;
F = 0;
G = 0;
M1 = 0;
M2 = 0;
if exist('ivalues') == 0
ivalues = [S0 S1 A B C D X Y ...
	W Z E F G M1 M2];
end
% rate constants and constant expressions
sourceS0f= 1;
fa0= 10;
fb0= 8;
b1= 0.1;
f1= 5;
f2= 60e-1;
b2= 0.02e+1;
sinkCf= 10;
sourceXb= 99;
sourceXf= 1;
sinkYb= 11;
sinkYf= 9;
sinkZb= 1.3;
sinkZf= 1;
gg= 0;
hh= 10;
ii= 5;
m1= 0;
m2= 0;
v2= 55.5;
ff= fa0;
v1= E + G;
v3= E + E;
global ode_rate_constants;
ode_rate_constants = [sourceS0f fa0 fb0 b1 f1 f2 b2 sinkCf sourceXb sourceXf sinkYb sinkYf ...
	sinkZb sinkZf gg hh ii m1 m2 v2 ff v1 v3];

% time interval
t0= 0;
tf= 5.0;

% call solver routine 
[t, y]= ode23s(@testMatlab_odes, [t0 tf], ivalues, odeset());

% map free node state vector names
S0 = y(:,1); S1 = y(:,2); A = y(:,3); B = y(:,4); C = y(:,5); D = y(:,6); X = y(:,7); Y = y(:,8); W = y(:,9); Z = y(:,10); 
E = y(:,11); F = y(:,12); G = y(:,13); M1 = y(:,14); M2 = y(:,15); 



% plot free nodes
figure(100);plot(t, S1, '.-');title('S1')
figure(101);plot(t, E, '.-');title('E')
figure(102);plot(t, G, '.-');title('G')

% plot expressions
sourceWf = sin(2*pi*t/0.1);
figure(103); plot(t, sourceWf, '.-');title('sourceWf=sin(2*pi*t/0.1)');
v1 = E + G;
figure(104); plot(t, v1, '.-');title('v1=E + G');
v3 = E + E;
figure(105); plot(t, v3, '.-');title('v3=E + E');
v4 = v3 + v1;
figure(106); plot(t, v4, '.-');title('v4=v3 + v1');

% issue done message for calling/wrapper scripts
disp('Facile driver script done');

