% File generated by Facile version 0.53
%
function dydt = config_odes(t, y)

global event_flags;
global event_times

% state vector to node mapping
A = y(1);
B = y(2);
X = y(3);
Y = y(4);

% constants and constant expressions
global ode_rate_constants;
f1 = ode_rate_constants(1);
f2 = ode_rate_constants(2);




% differential equations for independent species
dydt(size(y,1),1) = 0;
dydt(1)= - f1*A*B ;
dydt(2)= - f1*A*B ;
dydt(3)= + f1*A*B ;
dydt(4)= + f1*A*B ;


