% File generated by Facile version 0.53
%
% initial values (free nodes only)
A = 0;
B = 0;
%X = 0;
%Y = 0;
if exist('ivalues') == 0
ivalues = [A B X Y];
end
% rate constants and constant expressions
%f1= 1.1;
%f2= 100;
global ode_rate_constants;
ode_rate_constants = [f1 f2];

% time interval
t0= 0;
tf= 1.5;

% call solver routine 
global event_times;
global event_flags;
[t, y, intervals]= config_ode_event(@ode45, @config_odes, [t0:0.01:tf], ivalues, odeset('MaxStep',0.01,'RelTol',1e-3), [0.2 0.4 0.6], [10], [1e-4], [1e-6]);

% map free node state vector names
A = y(:,1); B = y(:,2); X = y(:,3); Y = y(:,4); 





% issue done message for calling/wrapper scripts
disp('Facile driver script done');

