% File generated by Facile version 0.53
%
tic;
global ode_tot_cputime;
global ode_num_calls;
ode_tot_cputime = 0.0;
ode_num_calls = 0;

% initial values (free nodes only)
poisson_ivals;

% rate constants and constant expressions
poisson_rates;

% time interval
t0= 0;
tf= 10;

% call solver routine 
lsode_options("maximum step size",10.0)
y= lsode(@poisson_odes, ivalues, (t=[t0:0.1:tf]'), [4 8]);

% map free node state vector names
D = y(:,1); A = y(:,2); 



% plot free nodes
figure(100);plot(t, A, '.-', 'markersize', 14);title('A')


str = sprintf('ODE STATS: num ode calls=%d, tot time=%f, avg time=%fms',ode_num_calls, ode_tot_cputime, ode_tot_cputime/ode_num_calls*1000);
disp (str)

% issue done message for calling/wrapper scripts
str = sprintf('Facile driver script done (elapsed time %f)',toc);
disp (str)

