//
// File generated by Facile version 0.53
//

// Custom header file
#include "poissonCVODE.h"

int main() {

  double ivalues[NEQ];
  double rates[1];

  // initial values (free nodes only)
  ivalues[0] = 1; // D
  ivalues[1] = 0; // A

  // rate constants
  rates[0] = 1;

  // call solver
  std::vector<realtype> *aT = new std::vector<realtype>;
  std::vector<realtype> *aY = new std::vector<realtype>;

  cvode_sim_poisson(ivalues, rates, aT, aY);

  delete aT;
  delete aY;

  return (0);
}
