% File generated by Facile version 0.53
%
function dydt = poisson_odes(y, t)

global ode_tot_cputime;
global ode_num_calls;
ode_start_time = cputime;
ode_num_calls = ode_num_calls + 1;
% state vector to node mapping
D = y(1);
A = y(2);

% constants and constant expressions
global ode_rate_constants;
d = ode_rate_constants(1);



% dynamic rate expressions
k = t/4*10*(t>=4 && t<8);

% differential equations for independent species
dydt(size(y,1),1) = 0;
dydt(1)= 0;
dydt(2)=  + k*D - d*A;


ode_end_time = cputime;
ode_tot_cputime = ode_tot_cputime + (ode_end_time - ode_start_time);
