% Script to run Driver generated by facile.pl
clear all; close all;

d = 1;
poissonDriver; 

% Sample values of outputs for future reference
disp('A= '); disp([A(10) A(30) A(60) A(end)]);
disp('D= '); disp([D(10) D(30) D(60) D(end)]);

