% File generated by Facile version 0.53
%
function dydt = steady_state_odes(t, y)

global event_flags;
global event_times

% state vector to node mapping
X = y(1);
Y = y(2);
Z = y(3);

% constants and constant expressions
global ode_rate_constants;
k_sinkx = ode_rate_constants(1);
k_sinky = ode_rate_constants(2);
k_sinkz = ode_rate_constants(3);



% dynamic rate expressions
k_srcx = 2*(t>=50 && ~event_flags(3));
k_srcy = 3*(event_flags(4));
k_srcz = 4*(event_flags(6));

% differential equations for independent species
dydt(size(y,1),1) = 0;
dydt(1)= + k_srcx - k_sinkx*X ;
dydt(2)= + k_srcy - k_sinky*Y ;
dydt(3)= + k_srcz - k_sinkz*Z ;


