<html>
<?php
### PHP code to run facile remotely.  Outputs two pages
### (1) welcome form to enter facile options and upload input file.  Sending this forms displays (2).
### (2) facile output.

### If this file or facile are moved around, it may be necessary to modify the following lines:
### i)  $upload_dir_base='./wd/';  # this is the working directory where upload and output files live.
### ii) rhs of variable $command.  This is the location of facile.

### Other things to keep in mind:
### a) The examples on the welcome page should be located on the same directory as this file, otherwise
###    make sure you change the appropriate ls command send by PHP.  Also examples assumed to be .eqn
### b) Files bigger than 50K are not accepted.  This limit can be modified.
### c) All subdirectories below the working directory older than 5 min are removed.  This can be modified.

if (!$_POST["uploadSent"]){ ### all html within this block is the welcome page 
  ?>
  <p>
    Welcome to the facile web interface.  Please click <A HREF="help.txt" target="_blank"> here </A> for instructions.
    <p>
  <form enctype="multipart/form-data" method="POST" action="<?php $_SERVER['PHP_SELF']?>"> 
    upload input file: <input type="file" name="userfile" size="40" dsdfsd>
    <p>
    <input type="hidden" name="uploadSent" value="1">
       facile options (e.g.,-rM): <input type="text" size="80" name="options">
    <p>
    <input type="submit" value="upload file and run facile">
    </form>
    <p>=======================================<P>
    Examples of input files:
  (click to view or right-click to download and edit)
    <p>
    <?php
    ### list all example files (assume that these files have extensions .eqn)
    $ls_out=`ls *.eqn`;
  $ls_out=preg_split("/\s+/ ",$ls_out);
  foreach($ls_out as $ls_each){
    echo "<p>";
    echo "<A HREF=\"$ls_each\" target=\"_blank\"> $ls_each </A>";
  }
 }

if ($_POST["uploadSent"]){ ### all html within this block is output page

  ### sort out file names and the download itself
  echo "<p>";
  $time=time();
  $upload_dir_base='./wd/'; # this is the working directory where upload and output files live.
  $upload_dir = $upload_dir_base.$time.'/';
  `mkdir $upload_dir`;# create working directory
  $upload_file_name = basename($_FILES['userfile']['name']);
  $upload_file_name_pref=preg_split("/\./",$upload_file_name);#filenames with space or several dots may fail?
  $upload_file_name_pref=$upload_file_name_pref[0];
  $upload_file_name_full = $upload_dir . $upload_file_name;
  if($_FILES['userfile']['size']>50000){
    echo "Error: file is too big to load into server.  Please contact authors to increase upload limit";
  } elseif (!move_uploaded_file($_FILES['userfile']['tmp_name'], $upload_file_name_full)) {
    echo "Error: upload failed";
    echo "<p>";
  } else {

  ### clean up options
  $opt=$_POST["options"];
  $opt=preg_replace('/\W/','',$opt);
  $opt=preg_replace('/\_/','',$opt);
  $opt=preg_replace('/\d/','',$opt);

  ### build the file names that will contain error and output
  $error_facile_file_name=$upload_dir.'errorOut.txt';
  $output_facile_file_name=$upload_dir.'outputOut.txt';
  ### run commands
  $command='/cnd0/home/fs226/bin/convEqns/eqnconvert.pl -'.$opt.' '.$upload_file_name_full.' 2> '.$error_facile_file_name;
  `$command`;
  $command='/cnd0/home/fs226/bin/convEqns/eqnconvert.pl -'.$opt.' '.$upload_file_name_full.' > '.$output_facile_file_name;
  `$command`;

  ###  remove file that was uploaded
  `rm $upload_file_name_full`; ### although the whole directory will be cleaned up later, it is safer to get rid of upload file soon.

  ### print error and output to screen
  $str_e = file_get_contents($error_facile_file_name);
  $str_o = file_get_contents($output_facile_file_name);
  $str_e = preg_replace('/\/.+\//','',$str_e);# don't give too much info on error.  Get rid of paths.
  echo "<p>";
  print "<pre>".$str_e."</pre>";
  echo "<p>---------------------------------<p>";
  echo "facile says:";
  print "<pre>".$str_o."</pre>";
  echo "<p>---------------------------------<p>";

  ### list  all files generated by facile
  echo "facile generated the following files:<p>";
  $for_ls=$upload_dir.$upload_file_name_pref.'*.*';
  $ls_out=`ls $for_ls`;
  $ls_out=preg_split("/\s+/ ",$ls_out);
  foreach($ls_out as $ls1){
    echo "<p>";
    echo "<A HREF=\"$ls1\" target=\"_blank\"> $ls1 </A>";
  }
  echo "<p>---------------------------------<p>";

  ### remove older directories
  $ls_out=`ls $upload_dir_base`;
  $ls_out=preg_split("/\s+/ ",$ls_out);
  $ls_out=array_filter($ls_out); #clear empty elements
  foreach($ls_out as $ls_each){
    $diff=$time-$ls_each;
    if($diff>5*60){
      $arg_rm= $upload_dir_base.$ls_each;
      `rm -fr $arg_rm`;
    }
  }

  }### end if upload ok

  ### continue form 
  ?>
    <form method="POST" action="<?php $_SERVER['PHP_SELF']?>">
       <?php
  echo "<input type=\"submit\" value=\"continue\">";
  echo "</form>";
  }

?>

</html>